---
# wait for key
- name: wait for public key creation
  ansible.builtin.wait_for:
    path: '{{ rustdesk.hbbs_data_dir }}/id_ed25519.pub'
    state: present

- name: key is in vault -> set them
  block:
    - name: stop container hbbs
      community.docker.docker_container:
        name: "{{ item }}"
        state: stopped
      with_items:
        - hbbs
        - hbbr

    - name: copy id_ed25519.pub
      ansible.builtin.template:
        src: "id_ed25519.pub.j2"
        dest: "{{ rustdesk.hbbs_data_dir }}/id_ed25519.pub"
        owner: root
        group: root
        mode: "0644"

    - name: copy id_ed25519
      ansible.builtin.template:
        src: "id_ed25519.j2"
        dest: "{{ rustdesk.hbbs_data_dir }}/id_ed25519"
        owner: root
        group: root
        mode: "0644"

    - name: start container hbbs
      community.docker.docker_container:
        name: "{{ item }}"
        state: started
      with_items:
        - hbbs
        - hbbr
  when: vault_rustdesk.id_ed25519.pub is defined and vault_rustdesk.id_ed25519.pub|length>0

# read public key
- name: read public key
  ansible.builtin.slurp:
    src: "{{ rustdesk.hbbs_data_dir }}/id_ed25519.pub"
  register: rustdesk_key

# display public key
- name: display public key
  ansible.builtin.debug:
    msg: "The Rustdesk server public key is: {{ rustdesk_key['content'] | b64decode }}"
...